### ISSUE TITLE
Fails to compile with GHC 8.0.1

### ISSUE THREAD

**Issue by expipiplus1** [danr/genifunctors#8]
GHC's output:

```
[1 of 1] Compiling Data.Generics.Genifunctors ( Data/Generics/Genifunctors.hs, dist/build/Data/Generics/Genifunctors.o )

Data/Generics/Genifunctors.hs:285:17: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ _ tvs cs _
      In the pattern: TyConI (DataD _ _ tvs cs _)
      In a case alternative:
          TyConI (DataD _ _ tvs cs _) -> return (map unPlainTv tvs, cs)
```
